name: TEST

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'test and run!'
        required: false
        
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: | ls
